---
- name: OpenVPN
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: robertdebock.openvpn

  tasks:
    - name: Install iptables-persistent
      ansible.builtin.package:
        name: iptables-persistent
        state: present

    - name: Copy iptables rules
      ansible.builtin.copy:
        src: ./iptables.rules.v4
        dest: /etc/iptables/rules.v4
        mode: "0644"
      register: iptables_rules

    - name: Restore iptables
      community.general.iptables_state:
        ip_version: ipv4
        path: /etc/iptables/rules.v4
        state: restored
      async: "{{ ansible_timeout }}"
      poll: 0
      when: iptables_rules.changed

    - name: Apply the routing rule so that traffic can leave the VPN
      ansible.builtin.iptables:
        table: nat
        chain: POSTROUTING
        source: 10.89.0.0/24
        out_interface: eth0
        jump: MASQUERADE
      when: iptables_rules.changed

    - name: Save iptables
      community.general.iptables_state:
        ip_version: ipv4
        path: /etc/iptables/rules.v4
        state: saved
      when: iptables_rules.changed

    - name: Allow IPv4 traffic forwarding in kernel
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        sysctl_set: yes
        reload: yes

    - name: Copy OpenVPN server configuration
      ansible.builtin.copy:
        src: ./server.conf
        dest: /etc/openvpn/server.conf
        mode: "0644"
      notify: Restart openvpn

    - name: Slurp pki file contents
      ansible.builtin.slurp:
        src: "{{ item }}"
      loop:
        - /etc/openvpn/easy-rsa/pki/ca.crt
        - /etc/openvpn/easy-rsa/pki/issued/client.crt
        - /etc/openvpn/easy-rsa/pki/private/client.key
        - /etc/openvpn/easy-rsa/pki/ta.key
      register: slurp

    - name: Parse slurp results
      set_fact:
        pki_files: "{{ pki_files | default({}) | combine({ item.source: item.content | b64decode }) }}"
      loop: "{{ slurp.results }}"
      no_log: true

    - name: Create OpenVPN client profile
      ansible.builtin.template:
        src: client.ovpn.j2
        dest: "~/profile.ovpn"
        mode: "0640"
      vars:
        remote: "{{ inventory_hostname }}"
        ca: '{{ pki_files["/etc/openvpn/easy-rsa/pki/ca.crt"] }}'
        cert: '{{ pki_files["/etc/openvpn/easy-rsa/pki/issued/client.crt"] }}'
        key: '{{ pki_files["/etc/openvpn/easy-rsa/pki/private/client.key"] }}'
        ta: '{{ pki_files["/etc/openvpn/easy-rsa/pki/ta.key"] }}'
      become: no

    - name: Copy OpenVPN client profile to the localhost
      ansible.builtin.fetch:
        src: ~/profile.ovpn
        dest: ./
        flat: yes
      become: no
